-- Generated by Mocodo 4.2.1

CREATE TABLE users_gmail (
  PRIMARY KEY (id_utilisateur),
  id_utilisateur       int(110) NOT NULL,
  nom_utilisateur      VARCHAR(236),
  prenom_utilisateur   VARCHAR(236),
  mail_utilisateur     VARCHAR(236),
  password_utilisateur VARCHAR(236)
);
