-- Generated by Mocodo 4.2.1

CREATE TABLE UTILISATEUR (
  PRIMARY KEY (id_utilisateur),
  id_utilisateur       VARCHAR(42) NOT NULL,
  nom_utilisateur      VARCHAR(42),
  prenom_utilisateur   VARCHAR(42),
  mail_utilisateur     VARCHAR(42),
  password_utilisateur VARCHAR(42)
);
